PREFIX ars3d: <http://java-dev.rgzm.de/ars#>
PREFIX ars: <http://ars3D/documentation/ontology/arsonto#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX sci: <http://www.ics.forth.gr/isl/CRMsci/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?feature ?obs ?otype ?statement WHERE {
?feature crm:P62_depicts ?n_obs.
?n_obs rdfs:label ?obs.
?n_obs sci:O8_observed ?n_obs2.
?n_obs2 <http://www.cidoc-crm.org/cidoc-crm/P2:has_type> ?otype.
OPTIONAL {
?statement a ars:Statement.
?statement rdfs:label ?slabel.
FILTER(?obs = ?slabel)
}
} ORDER BY ASC(?feature)